---
kind: pipeline
type: docker
name: default

steps:
  - name: goreleaser
    image: goreleaser/goreleaser
    pull: if-not-exists
    commands:
      - cd backend
      - goreleaser build --snapshot --rm-dist

  - name: ui-build
    image: kameshsampath/drone-ci-extension-ui-base
    pull: if-not-exists
    environment:
      # this is required by Docker Extension to load
      # static files from extension path on the Host
      PUBLIC_URL: .
      BROWSER: none
      CI: false
    commands:
      - cd ui
      - pnpm install
      - pnpm run clean && pnpm run build

  - name: build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      dry_run: true
      purge: false
      dockerfile: docker/Dockerfile.Standalone
      # https://github.com/thegeeklab/drone-docker-buildx/issues/141
      # cache_from: 
      #  - type=registry,ref=kameshsampath/drone-ci-docker-extension
      cache_to: type=registry,ref=kameshsampath/drone-ci-docker-extension
      repo: drone/drone-ci-docker-extension
      tag:
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
      # keep the core context to minimum as we load named contexts
      context: docker
      named_context:
        - dist=backend/dist
        - ui=ui/build
        - scripts=backend/scripts
        - etc=etc
    volumes:
    - name: dockersock
      path: /var/run/docker.sock

volumes:
   - name: dockersock
     host:
       path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: build-base

steps:
  - name: build
    image: docker/buildx-bin
    privileged: true
    pull: if-not-exists
    commands: 
    # settings:
    #   daemon_off: true
    #   dockerfile: docker/Dockerfile.pnpm
    #   repo: kameshsampath/drone-ci-extension-ui-base
    #   # https://github.com/thegeeklab/drone-docker-buildx/issues/141
    #   # cache_from: 
    #   #  - "type=registry,ref=kameshsampath/docker-extension-ui-cache"
    #   cache_to: "type=registry,ref=kameshsampath/docker-extension-ui-cache"
    #   tag:
    #     - latest
    #   platforms:
    #     - linux/amd64
    #     - linux/arm64
    #   context: ui
    volumes:
    - name: dockersock
      path: /var/run/docker.sock

volumes:
   - name: dockersock
     host:
       path: /var/run/docker.sock
